### ISSUE TITLE
Missing 90.1-2010 capacity between 1-1.5 in motor efficiency data

### ISSUE THREAD

**Issue by lzwang26** [pnnl/building-energy-standards-data#47]
See below:
https://github.com/pnnl/building-energy-standards-data/blob/76f1efb2045f745143f0804542a95a71daf87493/building_energy_standards_data/database_files/hvac_minimum_requirement_motors_90_1.json#L2858-L2881

**Comment by AmmarDeh** [comment]
@lzwang26 ASHRAE 90.1 Table 10.8A lists "NR" for open motors with number of poles of 2 indicating that there is no requirement and hence the entry was not included in the database.

**Comment by lzwang26** [comment]
> @lzwang26 ASHRAE 90.1 Table 10.8A lists "NR" for open motors with number of poles of 2 indicating that there is no requirement and hence the entry was not included in the database.

@AmmarDeh Thank you for the information! I will close it.
