### ISSUE TITLE
No module named 'building_energy_standards_data.database_tables.hvac_minimum_requirements_computer_room_air_conditioners_90_1' 

### ISSUE THREAD

**Issue by jiangyilin123** [pnnl/building-energy-standards-data#87]
I need to disable some unknown or non-existing tables in the file `~\building-energy-standards data\building_energy_standards_data\database_tables\__init__.py`  in order to create the database.

<img width="502" alt="no_module" src="https://github.com/user-attachments/assets/3d7a5ece-dea1-4f0b-b5d9-594f6913ce04">

**Comment by lymereJ** [comment]
@jiangyilin123 - Could you please share your script so we can see how you generate the database?

**Comment by jiangyilin123** [comment]
@lymereJ. Please close this. These data were accidentally deleted from my branch when I started to work on it.
