### ISSUE TITLE
No python file in data_tables for hvac_minimum_requirements_water_source_heat_pumps_heating/cooling

### ISSUE THREAD

**Issue by jiangyilin123** [pnnl/building-energy-standards-data#89]
I couldn't find the .py file in database_tables, but I found these JSON files in database_files. 

This led to the following warnings:
<img width="986" alt="image" src="https://github.com/user-attachments/assets/a5acbd9f-deab-4dff-97c3-ed497bf89881">

**Comment by lymereJ** [comment]
These tables have been depreciated. Minimum efficiency requirements for water source heat pumps are now in the `hvac_minimum_requirements_heat_pump_cooling/heating_*` tables.

**Comment by jiangyilin123** [comment]
Should we delete JSON files in database_files?

**Comment by lymereJ** [comment]
Yes, I'll remove them and also the references that generate these warnings. Thanks!
